#■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■#
#	ファイル名	：	/Mul_light/Kernel/FS/Makefile
#	概要		：	ファイルシステムMakefile
#	詳細		：	ファイルシステムのメイクルールです。
#	責任者		：	佐合 秀昭
#■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■#



#■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■#
#	変数定義
#■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■#
#ファイルシステムソース
FS_SOURCE		+= FS.cpp
FS_SOURCE		+= VFS.cpp

FS_SOURCE		+= ISO9660.cpp
FS_SOURCE		+= Joliet.cpp

FS_SOURCE		+= Keyboard.cpp
FS_SOURCE		+= Mouse.cpp

#ドライバディレクトリ
FS_DIRECTORY	+= ISO9660
FS_DIRECTORY	+= Joliet
FS_DIRECTORY	+= RockRidge
FS_DIRECTORY	+= Keyboard
FS_DIRECTORY	+= Mouse
FS_DIRECTORY	+= VFS



#■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■#
#	End of file
#■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■#

