#■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■#
#	ファイル名	：	/Mul_light/Kernel/DM/Makefile
#	概要		：	ドライバソース列挙
#	詳細		：	ドライバのコンパイル対象にするソースを記述します。
#	責任者		：	佐合 秀昭
#■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■#



#■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■#
#	変数定義
#■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■#
#デバイス管理ソース
DR_SOURCE		+= DM.cpp
DR_SOURCE		+= GDDM.cpp GDDM_DD2Msg.cpp
DR_SOURCE		+= GDDQ.cpp

#ドライバソース
DR_SOURCE		+= Driver.cpp

DR_SOURCE		+= PIC.cpp
DR_SOURCE		+= PIT.cpp
DR_SOURCE		+= RTC.cpp
DR_SOURCE		+= PCI.cpp

DR_SOURCE		+= PS2Keyboard.cpp
DR_SOURCE		+= PS2Mouse.cpp

#DR_SOURCE		+= BMIDE.cpp

DR_SOURCE		+= ATA.cpp
DR_SOURCE		+= ATA_Init.cpp
DR_SOURCE		+= ATA_CmdPublish.cpp
DR_SOURCE		+= ATA_CmdProt.cpp
DR_SOURCE		+= ATA_IO.cpp

#ドライバディレクトリ
DR_DIRECTORY	+= ATA
DR_DIRECTORY	+= PCI
DR_DIRECTORY	+= PIC
DR_DIRECTORY	+= PIT
DR_DIRECTORY	+= PS2Mouse
DR_DIRECTORY	+= PS2Keyboard
DR_DIRECTORY	+= RTC



#■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■#
#	End of file
#■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■#

